name: country_code_manager
description: "This package is used to get country code and country name from country code."
version: 1.1.10
repository: https://github.com/mrjake34/country_code_manager
homepage: https://www.efestech.com.tr

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  very_good_analysis: ^6.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - locale/
    - flags/
